version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillvault-api
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - EmailSettings__SmtpUser=${EmailSettings__SmtpUser}
      - EmailSettings__SmtpPass=${EmailSettings__SmtpPass}
      - Gemini__ApiKey=${Gemini__ApiKey}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: skillvault-frontend
    depends_on:
      - api
    ports:
      - "80:80"
