databases:
  - name: skillvault-db
    databaseName: skillvault
    user: skillvault_admin
    plan: free

services:
  - type: web
    name: skillvault-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: skillvault-db
          property: externalConnectionString
